# Generated by Django 2.2.2 on 2019-06-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('gps_x', models.CharField(max_length=250)),
                ('gps_y', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=50)),
                ('gps_x', models.CharField(max_length=250)),
                ('gps_y', models.CharField(max_length=250)),
                ('opening_time', models.TimeField(blank=True)),
                ('closing_time', models.TimeField(blank=True)),
                ('sample_pic', models.CharField(max_length=500)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Location')),
            ],
            options={
                'db_table': 'Places',
            },
        ),
    ]
