# Generated by Django 2.2.2 on 2019-06-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_tourist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('place_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(max_length=1)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Place')),
                ('tourist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Tourist')),
            ],
            options={
                'db_table': 'Place_Reviews',
            },
        ),
    ]
