# Generated by Django 2.2.2 on 2019-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0005_place_offday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='otp',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
