# Generated by Django 2.2.2 on 2019-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0006_auto_20190623_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='rating',
            field=models.CharField(max_length=1),
        ),
    ]
