# Generated by Django 2.2.2 on 2019-07-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0008_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=75)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'Inboxes',
            },
        ),
    ]
