# Generated by Django 2.2.1 on 2019-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0009_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
