# Generated by Django 2.2.2 on 2019-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0011_auto_20190709_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='passport_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
