# Generated by Django 2.2.2 on 2019-07-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0012_auto_20190710_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='offday',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
