# Generated by Django 2.2.1 on 2019-07-23 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0014_remove_tourist_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
