# Generated by Django 2.2.2 on 2019-07-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0017_auto_20190724_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesuggestion',
            name='suggested_location_id',
            field=models.CharField(max_length=6),
        ),
    ]
