# Generated by Django 2.2.4 on 2019-09-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0018_auto_20190724_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesuggestion',
            name='environment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
