# Generated by Django 2.2.4 on 2019-09-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0019_placesuggestion_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placesuggestion',
            name='environment',
        ),
    ]
