# Generated by Django 2.2.1 on 2019-09-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0021_placesuggestion_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placesuggestion',
            name='average_rating',
        ),
    ]
