# Generated by Django 2.2.1 on 2019-09-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0022_remove_placesuggestion_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='aveage_rating',
            field=models.CharField(default='', max_length=1),
        ),
    ]
