# Generated by Django 2.2.2 on 2019-06-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Places', '0007_auto_20190623_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('stand_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('gps_x', models.CharField(max_length=250)),
                ('gps_y', models.CharField(max_length=250)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Location')),
            ],
            options={
                'db_table': 'Stands',
            },
        ),
    ]
