# Generated by Django 2.2.2 on 2019-06-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandToStandCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_description', models.CharField(max_length=800)),
                ('stand1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations_standtostandcommunication_related', to='Transportations.Stand')),
                ('stand2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transportations.Stand')),
            ],
            options={
                'db_table': 'Stand_To_Stand',
                'unique_together': {('stand1_id', 'stand2_id')},
            },
        ),
    ]
