# Generated by Django 2.2.4 on 2019-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportations', '0002_standtostandcommunication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTransport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('route', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'PublicTransports',
            },
        ),
        migrations.AddField(
            model_name='stand',
            name='stand_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='StandToStandCommunication',
        ),
    ]
