# Generated by Django 2.2.2 on 2019-06-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Places', '0007_auto_20190623_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('gps_x', models.CharField(max_length=250)),
                ('gps_y', models.CharField(max_length=250)),
                ('opening_time', models.TimeField(blank=True)),
                ('closing_time', models.TimeField(blank=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.Location')),
            ],
            options={
                'db_table': 'Restaurants',
            },
        ),
    ]
