# Generated by Django 2.2.2 on 2019-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'Foods',
            },
        ),
    ]
